### ISSUE TITLE
inaturalistjs: liftoff

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalistjs#1]
inaturalistjs should be an npm package that allows a JavaScript client to create, read, update, and delete iNaturalist records using JavaScript objects and the [iNat API](http://api.inaturalist.org/v1/docs/). It should use the [Fetch standard](https://fetch.spec.whatwg.org/) and return Promises for all methods. I think this will make it a lot easier for us to build js apps.

Putative spec for now:

- [x] search observations and return iNat model objects
- [x] create identifications
- [x] create comments
- [x] authenticate requests with a Rails CSRF token
- [x] wrap it all up in a package that can be installed and managed with NPM

Thoughts

* Would it make sense to make a separate package for the models and share them between this and https://github.com/inaturalist/iNaturalistAPI? 
* Should this use es6 or will that make it impossible to use with node and angular 1? Do we care about that?

**Comment by pleary** [comment]
I'm going to call this complete.

I don't think it's necessary to create a separate package for models. I eventually realized the models in node will be quite different as they are based on turning ES and DB records into a standard format, and the models here are all based on the assumption they are already in the standard format. I think fact that we, and other consumers of this library, can use these models we return is good enough for now.

This code currently does assume ES6, and I think that's OK to. Better off staying with forward-looking standards as long as they are not too tricky to implement, and backwards compatible. Babel is making that possible.
