### ISSUE TITLE
Support React Native

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalistjs#16]
The biggest blocker for use in React Native is our dependency on https://www.npmjs.com/package/isomorphic-fetch. We need that in the browser and in our node API, so we don't want to get rid of it, but I guess we do want to make the choice of fetch package configurable, unless there's some other way to support React Native, the browser, and node.

**Comment by jtklein** [comment]
Hej,
I have just found this issue here. This is just to let you know that I have used parts of this library in RN, so far all the public methods seem to work without problems and I was able to create comments (have not checked other methods and all params yet).
Cheers

**Comment by kueda** [comment]
Thanks for the reminder, I think we mostly addressed this in https://github.com/inaturalist/inaturalistjs/pull/17. Can you link to your RN project? I'm curious!

**Comment by jtklein** [comment]
No worries.
Have just started to work on a small app to make the identification process faster for me.
https://github.com/jtklein/inat-identify
