### ISSUE TITLE
Error thrown for API call has no text

### ISSUE THREAD

**Issue by jtklein** [inaturalist/inaturalistjs#20]
When receiving a response from the default API the field `statusText` is empty. For this reason, the error thrown in the method `thenText` is empty as well.
in inaturalist_api.js line 182
`
      var error = new Error( response.statusText );
`
This happened to me in a 200 and 401 response as well.

It would help if the error thrown was more informative.

<img width="317" alt="bildschirmfoto 2018-10-08 um 23 31 28" src="https://user-images.githubusercontent.com/17345891/46660584-9db2e200-cbb7-11e8-8009-68638d2193bf.png">

**Comment by kueda** [comment]
Can you paste in some of your code? The way we usually use it is to use the `catch(e)` method on the Promise, which takes an error object as its argument. That's not particularly more informative, but there's not much more we can provide in a [401 HTTP error](https://tools.ietf.org/html/rfc7235#page-6), which just means authentication failed, i.e. the username and password didn't match a known user. I feel like the best we could provide there would be to set `statusText` to `Unauthorized`, which doesn't seem much more helpful to me.

**Comment by jtklein** [comment]
Sure! The way I used the method from the lib, e.g. for creating an identification:
`
    inatjs.identifications
      .create(identification, options)
      .then(c => {
        console.log('identification', c);
      })
      .catch(e => {
        console.log('Error in creating identification', e);
      });
`

The error output then becomes:
`
Error in creating identification Error
    at thenText (inaturalistjs.js:283)
    at tryCallOne (core.js:37)
...
`

I have seen that the `thenText()` method also adds the response object to the error, so I can log that out too, to find out what the error was. Personally, I find it nicer if there is an error message that is explanatory. And I am not sure if it is standard to add some fields to the Error. Maybe you can take the `response.headers.map.status` as error message, or send back some text in statusText as you say. Or add to the readme that there is extra information in `Error.response`.
