### ISSUE TITLE
Explain getting API token

### ISSUE THREAD

**Issue by jtklein** [inaturalist/inaturalistjs#21]
I had a lot of trouble finding out how to get an API token at runtime to use the package. I am not from a web dev background, so maybe for other people this is obvious. However, I think you also want to target this package for mobile developers. Anyway, I ended up checking out the Android's app source code, to find out what I needed to do. But for future users maybe it would be nice to add some more documentation.

Maybe it would be feasible to have some authentication inside of this package as well.

To clarify exactly which information was missing for me:
Documentation states that:
> For now, these are found at http://www.inaturalist.org/users/api_token .

A GET request to that site responded with HTML for sign in  page. The missing information was how to connect being authenticated from OAuth to this call. What I found in the Android App source was using an authorization header:
`
request.setHeader("Authorization", "Bearer " + mCredentials); 
`

**Comment by kueda** [comment]
Yeah, that was pretty vague, so I updated the README. Thanks.
