### ISSUE TITLE
bug: setConfig is not a function

### ISSUE THREAD

**Issue by PhearZero** [inaturalist/inaturalistjs#5]
:beetle: Need to expose setConfig in [inaturalistjs](https://github.com/inaturalist/inaturalistjs/blob/master/lib/inaturalistjs.js) or remove it from the [Readme.md](https://github.com/inaturalist/inaturalistjs#configuring-api-host)

**Comment by kueda** [comment]
Fixed in b958a2f6d8b9030168d92fd4ccd690335b9eda00
