### ISSUE TITLE
Add /search endpoint

### ISSUE THREAD

**Issue by albullington** [inaturalist/inaturalistjs#53]
For the iNat mobile redesign, we'll need a `/search` endpoint accessible via inatjs. This will be used similarly to header search on the web. It will also be used for various autocomplete searches (i.e. user autocomplete or projects autocomplete in Explore Filters).

`/search` already has API v2 support ([#283](https://github.com/inaturalist/iNaturalistAPI/issues/283))

**Comment by pleary** [comment]
search endpoint should be in place now and can be called with just `.search()` (all other methods are invoked like `.controller.action()`, but it made sense to me that since there are no other actions planned for the the search controller that we just call it without an additional action name)
