### ISSUE TITLE
Add /projects endpoint for fetching featured, nearby, user project lists 

### ISSUE THREAD

**Issue by albullington** [inaturalist/inaturalistjs#56]
Right now, we can only fetch from `/v2/projects/:id` via inatjs. We need a way to be able to fetch user subscribed projects, nearby projects, and featured projects on iNat mobile, so we'll also need a `/v2/projects` endpoint.

**Comment by pleary** [comment]
The endpoints`/users/:id/projects` for fetching user projects and `/projects` for search, including fetching nearby projects, should be available now
